api/urls.py
from api import views
from django.conf.urls import url

app_name = 'api'

urlpatterns = [
    url(r'^post/', views.PostView.as_view(), name="post"),
]

thumbnail/urls.py
from django.contrib import admin
from django.urls import path
from thumbnail import view
from api import urls as api_urls
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', view.index_view),
    path('admin/', admin.site.urls),
    path('api/v1/', include(api_urls), name="api"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=255)
    video = models.FileField(upload_to='post/video/%Y/%m/%d/', null=True, blank=True)  # NOQA
    thumbnail = models.FileField(upload_to='post/thumbnail/%Y/%m/%d/', null=True, blank=True)  # NOQA

api/views.py
import base64

import time
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from post.models import Post
from api.serializer import PostSerializer


class PostView(APIView):
    queryset = Post.objects.none()
    serializer_class = PostSerializer
    http_method_names = ['post', ]

    def post(self, request):
        title = request.POST.get('title', None)
        video = request.FILES['file']
        thumbnail = request.POST.get('thumbnail', None)
        format, imgstr = thumbnail.split(';base64,')
        ext = format.split('/')[-1]
        data = ContentFile(base64.b64decode(imgstr))
        myfile = "post/thumbnail/thumbnail-" + time.strftime("%Y-%m-%d-%H-%M-%S") + "." + ext  # NOQA
        fs = FileSystemStorage()
        filename = fs.save(myfile, data)
        Post.objects.create(title=title, video=video, thumbnail=filename)
        return Response("post saved successfully", status=status.HTTP_201_CREATED)  # NOQA

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">


    <title>I Love Django</title>
</head>
<body>
<div class="container">
    <div class="row">
        <nav class="navbar fixed-top navbar-dark bg-primary">
            <a class="navbar-brand" href="https://ilovedjango.com/">
                <img src="/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30"
                     class="d-inline-block align-top"
                     alt="">
                I Love Django
            </a>
        </nav>
    </div>
</div>

<div class="container" style="margin-top: 100px;">
    <h1>Create thumbnail from video and save it using Django</h1>
    <form id="createPostForm" enctype="multipart/form-data">
        <div class="form-group">
            <label for="Title">title</label>
            <input type="text" class="form-control" name="title" id="Title"
                   placeholder="title" required>
        </div>
        <div class="form-group">
            <label for="file">Video</label><br>
            <input type="file" name="file" id="file" accept="video/*" required>
        </div>

        <div class="form-group" id="thumbnailDiv" style="max-height: 140px">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

    <!-- Thumbnail Modal -->
    <div class="modal fade bd-example-modal-lg" id="videoModal" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Thumbnail</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" style="text-align: center">
                    <div class="container" style="text-align:center">
                        <video height="auto" width="100%" id="video" class="video-preview" controls="controls"/>
                    </div>
                    <button onclick="takeThumbnail()">capture</button>
                    <canvas id="canvas" style="display: none;"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<script>
    var CREATE_POST_URL = "{% url 'api:post' %}";
</script>
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
</body>

</html>